spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: example
    password: example
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate.integrator_provider: com.vladmihalcea.hibernate.type.util.ClassImportIntegrator
    hibernate:
      ddl-auto: create-drop
